### ISSUE TITLE
Some suggestions for implementing zilsd extensions in gcc and binutils

### ISSUE THREAD

**Issue by dongyasun** [riscv/riscv-zilsd#28]
Hi @christian-herber-nxp
The support for binutils（[https://github.com/nxp-auto-tools/binutils_zilsd/tree/zilsd）](https://github.com/nxp-auto-tools/binutils_zilsd/tree/zilsd%EF%BC%89) is not perfect, lacking recognition of zilsd extension. In addition, compressed Load/Store pair instructions (c.ld, c.sd, c.ldsp, c.sdsp) are not distinguished from zilsd extensions, as zcmlsd extensions.

The support for gcc(https://github.com/nxp-auto-tools/gcc_zilsd/tree/zilsd), whether the zilsd extension is reasonable as part of the `zi_subext `?.

**Comment by christian-herber-nxp** [comment]
thanks for your feedback. You had previously submitted an issue on the binutils project, and i think this is where it belongs. Here should be issues on what is contained in this repository, which is the specification itself. I am closing this issue here, and you can reopen the other one. 
Fyi, we are currently working on adding the notion of Zcmlsd. The current version of binutils was based on a previous version of the spec.
