### ISSUE TITLE
Do we need load/store pair with reversed order?

### ISSUE THREAD

**Issue by wangpc-pp** [riscv/riscv-zilsd#44]
For current load/store pair instructions, I think there is a problem to be solved.
I was thinking we can use Zilsd instructions in prologue/epilogue to spill/reload. However, currently, the order of spill and reload is reversed:
```
sw s0, 8(sp)
sw s1, 0(sp)
...
lw s0, 8(sp)
lw s1, 0(sp)
```

But, Zilsd instructions can only be in order, that is:
```
sw s0, 0(sp) 
sw s1, 8(sp)
...
lw s0, 0(sp)
lw s1, 8(sp)
```
I think there are two solutions:
* Reverse the order of spill/reload to match Zilsd, but we need to handle it specially in compiler and may have some ABI compatibility issues.
* Add instructions with reversed order. Since the src/dst registers are aligned, maybe we can use the LSB bit to indicate the order.

**Comment by tovine** [comment]
Interesting idea, I never thought about that. 
I think this would definitely be a common use case for Zilsd, so we should make it work somehow.
What would be the consequences of reversing the spill order to match these instructions (and is there a good reason it's spilling in this order now, or was it just an arbitrary decision)?

These reserved encodings were intended to be saved for "something useful" in the future, but if the ABI can't be adapted to fit then I think it would certainly qualify for using this encoding bit, as I imagine the potential improvements in code size and performance would be more than trivial. 
Does anyone have numbers on how common register spills are in typical software? 

Since this is an RV32-only extension then it's probably most relevant for embedded software where source distribution is the most common method and everything is built for the target platform at once, so ABI compatibility might not be a huge concern but it still happens (e.g. when commercial vendors distribute linkable precompiled versions of their libraries). Maybe it would be nice with some input from them on this point. @anderslindgren-iar?

**Comment by anderslindgren-iar** [comment]
The ABI doesn't say anything about the order in which the S-registers are saved on the stack, only that they should have the same value at the end of the function as they do in the beginning. Hence, the pair store/load instruction can be used in the prologue/epilogue, as they are defined today in Zilsd.

A compiler emits so called _backtrace_ information that encodes how all resources are stored. This is used, for example, by debuggers to present the call stack. All tools that want to get information about the S-registers on the stack should do so based on the backtrace information. This allows a compiler to change the layout based on the available instructions, like `cm.push` and `sd`.

**Comment by christian-herber-nxp** [comment]
The other thing I would like to add is that machines which implement Zilsd are likely to implement Zcmp, so optimizing prologue/epilogue does not sound promising to me. 

Indeed, there is a bit left with which a new mode could be defined. This should be done based on quantitative data. This could involve pre-incrementing, a different data size (e.g. load/store byte pair), or the reversed order. 
Also, the encoding space could of course be used for something load/store unrelated, if that gives the better bang for the buck.

The scope of this extension is fairly clear, and new proposals always welcome.
Based on Anders confirmation, closing the issue.
