### ISSUE TITLE
Unclarity about whether load/store pair are interruptible or not

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-zilsd#46]
Hi,

Version 0.9.0 of the specification states:

> It is implementation defined whether interrupts can also be taken during the sequence execution.

This note was completely clear. Unfortunately it has been removed from version 0.10, which now only has the following related remark (which is not fully clear)

> These decomposed sequences are interruptible.

What does the 'are interruptible' really mean? The decomposed sequenced 'shall be' interruptible or 'are allowed but not mandated to be' interruptible?

**Comment by tovine** [comment]
I think it's the latter, so software must not rely on the sequences to not be interrupted, but hardware can of course treat them as not interruptible.

**Comment by christian-herber-nxp** [comment]
The quoted text from v0.10 is only applicable to 4-byte aligned accesses.
I agree that the wording should likely be more precise.
It was a choice of the ARC to remove the quote from v0.9. My guess is that it is not necessary to explicitly specify this, as I guess it is implementation defined for any multi-cycle instruction to be interruptible or not.
So, for any possible change, which we could make during the public review, I would like the input of the ARC on that. @aswaterman: could you comment on this?

**Comment by aswaterman** [comment]
If memory serves, the ARC objected specifically to the words "It is implementation defined whether" because they don't add any meaning.  An implementation that chooses not to take interrupts in the middle is still a correct implementation of the clause "the sequence is interruptible", since there is inherent flexibility in the timing of interrupts.  A machine that chooses not to interrupt this sequence is equivalent to a machine for which these interrupts are always serendipitously delayed until just after the instruction retires.

**Comment by christian-herber-nxp** [comment]
closing as Andrew clarified this issue
